language: python
cache: pip
# Existing Python versions
python:
  - 3.4
  - 3.5
  - 3.6
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - mysql -u root --password="" --default-character-set=utf8 test < sql/test-dump.sql
env:
  global:
    - DB_HOST="127.0.0.1" DB_PASSWORD="" DB_USERNAME="root" DB_DATABASE="test"global
  matrix:
    - DB_HOST="127.0.0.1" DB_PASSWORD="" DB_USERNAME="root" DB_DATABASE="test"
install:
- pip install -r requirements.txt
- pip install nose
- pip install flake8
- pip install nose-cov
- pip install python-coveralls
script: nosetests --with-cov --cov api/ test/ && flake8 api/ src main.py test
after_success:
  - coveralls
